/**
 * DOMAIN CLASSES USED TO PRODUCE THE JSON AND XML OUTPUT FOR THE RESTFUL SERVICES.
 * <P>
 * THESE CLASSES CONTAIN THE JAXB ANNOTATIONS.
 *
 * @SINCE 1.0
 * @AUTHOR JWHITE
 * @VERSION 1.1
 */
package net.kolls.railworld.opening;